name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  api:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            rudio1/vaemobility:latest
            rudio1/vaemobility:${{ github.sha }}

  jobs:
    name: Build Jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.jobs
          push: true
          tags: |
            rudio1/vaemobility-jobs:latest
            rudio1/vaemobility-jobs:${{ github.sha }}
